baseURL                 = "https://earlparkfestival.com/"            # Your domain name. Must end with "/"
languageCode            = "en-us"                           # languageCode
title                   = "Earl Park Fall Festival"                    # Site title
theme                   = "introduction"
pygmentsStyle           = "monokai"                         # https://help.farbox.com/pygments.html
pygmentsCodefences      = true
enforce_ssl             = false
# disqusshortname       = ""                                # Enable Disqus for comments https://gohugo.io/content-management/comments
googleAnalytics         = "UA-23344414-3"                                # Enable Google Analytics https://gohugo.io/templates/internal/#google-analytics

[params]
    eventHead            = "Event"                            # Full name shows on blog post pages
    firstName           = "The 46th Earl Park Fall Festival"         # First name shows in introduction on main page
    tagLine             = "August 31st - September 3rd, 2018. Earl Park, Indiana."    # Appears after the introduction
    introHeight         = "large"                           # Input either 'medium' or 'large' or 'fullheight'
    themeStyle          = "light"                           # Choose 'light' or 'dark'
    avatar              = "img/about.jpg"                 # Path to image in static folder eg. img/avatar.png, or comment out to remove
    brochurepage1      = "docs/earl-park-brochure2018-page-001.jpg"
    brochurepage2      = "docs/earl-park-brochure2018-page-002.jpg"
    brochurepdf        = "docs/earl-park-brochure2018.pdf"
    bloodrive           = "img/bloodrive.jpg"
    email               = "info@earlparkfestival.com"       # Shows in contact section, or leave blank to omit
    localTime           = true                              # Show your current local time in contact section
    timeZone            = "America/New_York"                # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    dateForm            = "Jan 2, 2006"
    dateFormFull        = "Mon Jan 2 2006 15:04:05 EST"
    cacheBuster         = false                             # Add the current unix timestamp in query string for cache busting css assets (relevant in development mode)
    description         = "The Earl Park Fall Festival. Held annually on Labor Day weekend in Earl Park, Indiana. Free parking. No admission."    # Max 160 characters show in search results
    faviconFile         = "img/fav.ico"
    footerText          = ""                                # Text to override default footer text (markdown allowed)
    fadeIn              = true                              # Turn on/off the fade-in effect
    customCSS           = []                                # Include custom css files e.g. ["css/foo.css", "css/bar.css"]

    showEvent            = true                              # Show Events section on home page
    showSchedule        = true                              # Show Projects section on home page
    projectColumns      = "3"                               # Choose "2" or "3" columns for projects section
    placeHolderimg      = "/img/workday.jpg"                # For Projects without image
    showAllPosts        = false                             # Set 'true' to list all posts on home page, or set 'false' to link to separate blog list page
    showLatest          = true                              # Show latest blog post summary
    shareButtons        = true                              # On post pages, show share this social buttons

    # Share buttons
    shareTwitter        = true
    shareFacebook       = true
    sharePinterest      = false
    shareGooglePlus     = true

# Social icons appear in introduction and contact section. Add as many more as you like.
# Find icon names here: http://fontawesome.io/cheatsheet/

[[params.social]]
    url  = "https://twitter.com/EarlParkFest"
    icon = "twitter"

[[params.social]]
    url  = "https://facebook.com/EarlParkFallFestival"
    icon = "facebook"

[[params.social]]
    url  = "https://www.instagram.com/earlparkfest/"
    icon = "instagram"

[[params.social]]
    url  = "https://www.youtube.com/channel/UCPWOuWatPHTb53BlwXEzKWw"
    icon = "youtube"
